version: 0.2

phases:
    pre_build:
        commands:
            ### Login to Amazon ECR
             - echo Logging in to Amazon ECR...
             - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin abc$AWS_ACCOUNT_ID123.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
             - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
             - IMAGE_URI="${REPOSITORY_URI}:${TAG}"
             - IMAGE_LATEST="${REPOSITORY_URI}:latest"
    build:
        commands:
            ### Building the image 
             - echo Build started on `date`
             - docker build -t $IMAGE_URI -t $IMAGE_LATEST .
             - echo Build completed on `date`
    post_build:
        commands:
            ### Publish the docker images to ECR
            - echo Pushing the Docker images...
            - docker push $IMAGE_URI
            - docker push $IMAGE_LATEST
            - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "$IMAGE_URI" > images.json
artifacts:
  files: images.json